### ISSUE TITLE
Gable roofs generation

### ISSUE THREAD

**Issue by Andrej730** [prochitecture/bpypolyskel#12]
@polarkernel

Is it possible to make gable roofs with bpypolyskel?

<img src="https://user-images.githubusercontent.com/9417531/224919675-6a0c7acf-f332-4026-97bb-d0a2c5c0e426.png" width=50% height=50%>

The best idea I currently came up with is just generating hiped roof from the footprint and moving it's top vertices towards the edges that I want to be flattened.

<img src="https://user-images.githubusercontent.com/9417531/224920244-da333fc0-7e38-4c94-922a-e1d879448f9d.png" width=50% height=50%>

I tried to hack into `bpypolyskel.polygonize` and alter a part of the skeleton from `Subtree(source=Vector((0.0, -1.0)), height=1.0, sinks=[Vector((-1.0, -2.0)), Vector((1.0, -2.0))]` to `Subtree(source=Vector((0.0, 1.0)), height=1.0, sinks=[Vector((1.0, 2.0)), Vector((-1.0, 2.0))])` and setting height for the `skeleton_node3D` that's created from that subtree so it wouldn't be zero.

But the result was `poly2FacesGraph.faces()` returning inccorrect faces where same vertex appears more than once:
`[[0, 1, 5, 4], [3, 0, 4], [2, 1, 0, 3, 2, 5, 1, 2, 3, 4, 5]]` 
(expected something like `[[0, 1, 5, 4], [3, 0, 4], [2, 3, 4, 5], [1, 2, 5]]`)

Any suggestions?

@vvoovv did this need occur on Blender-OSM? how were you solving that problem?

**Comment by polarkernel** [comment]
It is difficult for me to answer without having the original data of your attempt. However, I don't think it is a good idea to tweak `bpypolyskel` to create gabled roofs, you will always run in special cases. There are easier algorithms for gabled roofs. I think, @vvoovv can give you some hints on how he did it in blender-osm.

**Comment by Andrej730** [comment]
I can provide the data I was using with `polygonize`:
```python
kwargs = {'faces': None,
 'firstVertIndex': 0,
 'height': 0.0,
 'holesInfo': None,
 'numVerts': 4,
 'tan': 0.0,
 'unitVectors': None,
 'verts': [Vector((-1.0, -2.0, 0.0)),
           Vector((1.0, -2.0, 0.0)),
           Vector((1.0, 2.0, 0.0)),
           Vector((-1.0, 2.0, 0.0))]}
```

**Comment by costika1234** [comment]
That's just a very simple roof with 2 planes that can be generated using simpler methods. As @polarkernel said, it's not even worth trying to think about adapting a hip roof for the general case due to so many corner cases. At some point you will have to have hips and valleys, and trying to figure out which parts can turn into gables is insanely difficult. 

If you have an application that allows you to manually edit the position of the vertices using some sort of drag tool, then it is quite easy to adapt the geometry and end up with gables in the desired locations. However, it sounds like you are trying to generate this automatically and have as many gables as possible, right?

**Comment by Andrej730** [comment]
That was just an example, I need it for much more complex shapes and polygonize does good job for creating this type of roof except I need to add some gables to it. I'm looking for a way to do it automatically from the roof footprint and list of edges of that footprint that suppose to have a gable.

**Comment by vvoovv** [comment]
That was already discussed in #9. The way to go would be to postprocess the results provided by bpypolyskel. It is not implemented in Blender-OSM
